const SUPABASE_URL='https://lfgukrnfuradrgofzxsz.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_VwhWvbGrfWR7jkJY5QKwyw_Ka14_Y-m';
const CLOUD_KEY='kyleos:phase1';
const LOCAL_KEY='kyleos:phase1:local';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});
let authUser=null,deferredPrompt=null,editingType=null;
const today=()=>new Date().toISOString().slice(0,10);
const seed=()=>({version:1,date:today(),habits:[{id:crypto.randomUUID(),name:'Scripture / Prayer',minimum:'Read and reflect on 3 verses',done:false},{id:crypto.randomUUID(),name:'Medication',minimum:'Take medication with water',done:false},{id:crypto.randomUUID(),name:'Training / Movement',minimum:'10 minutes of movement',done:false},{id:crypto.randomUUID(),name:'Evening Reset',minimum:'Prepare clothes and medication',done:false}],hydration:{amount:0,goal:100},priorities:[{id:crypto.randomUUID(),name:'Walk faithfully with Christ',done:false},{id:crypto.randomUUID(),name:'Become a better RBT',done:false},{id:crypto.randomUUID(),name:'Study for BCBA growth',done:false}]});
let state=loadLocal();
function normalize(s){const x={...seed(),...(s||{})};x.habits=Array.isArray(x.habits)?x.habits:[];x.priorities=Array.isArray(x.priorities)?x.priorities:[];x.hydration={amount:0,goal:100,...(x.hydration||{})};if(x.date!==today()){x.date=today();x.habits=x.habits.map(h=>({...h,done:false}));x.priorities=x.priorities.map(p=>({...p,done:false}));x.hydration.amount=0;}return x}
function loadLocal(){try{return normalize(JSON.parse(localStorage.getItem(LOCAL_KEY)))}catch{return seed()}}
function saveLocal(){localStorage.setItem(LOCAL_KEY,JSON.stringify(state));render();schedulePush()}
let pushTimer;function schedulePush(){setSync(authUser?'Saving…':'Local');clearTimeout(pushTimer);pushTimer=setTimeout(pushCloud,700)}
async function pullCloud(){if(!authUser||!sb)return;setSync('Syncing…');const{data,error}=await sb.from('app_data').select('data,updated_at').eq('user_id',authUser.id).eq('key',CLOUD_KEY).maybeSingle();if(error){setSync('Offline',true);return}if(data?.data){state=normalize(data.data);localStorage.setItem(LOCAL_KEY,JSON.stringify(state))}else await pushCloud();render();setSync('Synced')}
async function pushCloud(){if(!authUser||!sb){setSync('Local');return}const{error}=await sb.from('app_data').upsert({user_id:authUser.id,key:CLOUD_KEY,data:state},{onConflict:'user_id,key'});setSync(error?'Offline':'Synced',!!error)}
function setSync(text,offline=false){const el=document.getElementById('syncState');el.textContent=text;el.className='sync-pill '+(offline?'offline':text==='Synced'?'synced':'')}
const pct=(a,b)=>b?Math.round(a/b*100):0;
function row(item,type){return `<div class="item-row ${item.done?'done':''}"><input class="check" type="checkbox" data-toggle="${type}" data-id="${item.id}" ${item.done?'checked':''}><div><div class="item-title">${esc(item.name)}</div>${item.minimum?`<div class="item-sub">Minimum: ${esc(item.minimum)}</div>`:''}</div><button class="delete" data-delete="${type}" data-id="${item.id}" aria-label="Delete">×</button></div>`}
function esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){state=normalize(state);const hd=state.habits.filter(x=>x.done).length,pd=state.priorities.filter(x=>x.done).length;document.getElementById('habitScore').textContent=`${hd} / ${state.habits.length}`;document.getElementById('habitBar').style.width=pct(hd,state.habits.length)+'%';document.getElementById('waterScore').textContent=`${state.hydration.amount} / ${state.hydration.goal}`;document.getElementById('waterBar').style.width=Math.min(100,pct(state.hydration.amount,state.hydration.goal))+'%';document.getElementById('priorityScore').textContent=`${pd} / ${state.priorities.length}`;document.getElementById('priorityBar').style.width=pct(pd,state.priorities.length)+'%';document.getElementById('habitList').innerHTML=state.habits.map(h=>row(h,'habit')).join('')||'<p class="muted">No habits yet.</p>';document.getElementById('priorityList').innerHTML=state.priorities.map(p=>row(p,'priority')).join('')||'<p class="muted">No priorities yet.</p>';document.getElementById('waterGoal').value=state.hydration.goal;const next=state.habits.find(h=>!h.done)||state.priorities.find(p=>!p.done);document.getElementById('nextAction').textContent=next?(next.minimum||next.name):'Today’s commitments are complete.';document.getElementById('todaySummary').innerHTML=`<div class="today-line"><span>Habits</span><strong>${hd}/${state.habits.length}</strong></div><div class="today-line"><span>Hydration</span><strong>${state.hydration.amount}/${state.hydration.goal} oz</strong></div><div class="today-line"><span>Priorities</span><strong>${pd}/${state.priorities.length}</strong></div>`;bindRows()}
function bindRows(){document.querySelectorAll('[data-toggle]').forEach(el=>el.onchange=()=>{const list=el.dataset.toggle==='habit'?state.habits:state.priorities;const item=list.find(x=>x.id===el.dataset.id);if(item){item.done=el.checked;saveLocal()}});document.querySelectorAll('[data-delete]').forEach(el=>el.onclick=()=>{const key=el.dataset.delete==='habit'?'habits':'priorities';state[key]=state[key].filter(x=>x.id!==el.dataset.id);saveLocal()})}
function openDialog(type){editingType=type;document.getElementById('dialogTitle').textContent=type==='habit'?'Add habit':'Add priority';document.getElementById('minimumWrap').hidden=type!=='habit';document.getElementById('dialogName').value='';document.getElementById('dialogMinimum').value='';document.getElementById('itemDialog').showModal();document.getElementById('dialogName').focus()}
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(btn.dataset.view+'View').classList.add('active')});
document.getElementById('addHabitBtn').onclick=()=>openDialog('habit');document.getElementById('addPriorityBtn').onclick=()=>openDialog('priority');document.getElementById('dialogSave').onclick=e=>{const name=document.getElementById('dialogName').value.trim();if(!name){e.preventDefault();return}const item={id:crypto.randomUUID(),name,done:false};if(editingType==='habit')item.minimum=document.getElementById('dialogMinimum').value.trim();state[editingType==='habit'?'habits':'priorities'].push(item);saveLocal()};document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{state.hydration.amount=Math.max(0,state.hydration.amount+Number(b.dataset.water));saveLocal()});document.getElementById('waterReset').onclick=()=>{state.hydration.amount=0;saveLocal()};document.getElementById('waterGoal').onchange=e=>{state.hydration.goal=Math.max(1,Number(e.target.value)||100);saveLocal()};document.getElementById('refreshBtn').onclick=()=>authUser?pullCloud():render();
document.getElementById('signInBtn').onclick=async()=>{const email=document.getElementById('emailInput').value.trim();if(!email)return;const{error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});document.getElementById('authMessage').textContent=error?error.message:'Check your email for the sign-in link.'};document.getElementById('signOutBtn').onclick=()=>sb.auth.signOut();
async function updateAuth(session){authUser=session?.user||null;document.getElementById('signInBtn').hidden=!!authUser;document.getElementById('emailInput').hidden=!!authUser;document.getElementById('signOutBtn').hidden=!authUser;document.getElementById('authMessage').textContent=authUser?`Signed in as ${authUser.email}`:'Your data stays local until you sign in.';if(authUser)await pullCloud();else setSync('Local')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').hidden=false});document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBtn').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');sb?.auth.getSession().then(({data})=>updateAuth(data.session));sb?.auth.onAuthStateChange((_e,session)=>updateAuth(session));render();